### PR TITLE
fix(PublicPages): show spinner after login

### PR DESCRIPTION
**Pull request by fcoronelmakingsense**
- Fix spinner after login success before to load doppler app

image

### CODE REVIEW

**Comment by fcoronelmakingsense** [comment]
test this please

**Comment by fcoronelmakingsense** [comment]
test this please

**Comment by fcoronelmakingsense** [comment]
test http://cdn.fromdoppler.com/doppler-webapp/build2468/#/login

**Comment by cbernat** [comment]
Did you test your fix in shopify, reports for subscriber history, reports for gdpr, new features, and offline page? For the changes I see it's like it needs to be replicated everywhere 🤔

**Comment by fcoronelmakingsense** [comment]
> Did you test your fix in shopify, reports for subscriber history, reports for gdpr, new features, and offline page? For the changes I see it's like it needs to be replicated everywhere 🤔

Yes i checked! the change only affect public pages

**Pull request merged**
