### PR TITLE
DBR-198 - Login client

### PR DESCRIPTION
**Pull request by andresmoschini**
Hi team,

Well, I have reduced the scope of this PR.

By the moment, I am calling _DopplerLegacyClient_, and I am ready to get expected errors, but I am not dealing with them yet (See TODO notes).

I am also sending captcha to backend and restarting the session.

Basically, the pending work is dealing with expected errors. 

Could you review?

### CODE REVIEW

**Comment by VicThorX** [comment]
I do not understand much about React, but I think it's all okay.

Only I have 2 questions `userBlockedByPassword` informs that the user exists but fails when the password is not correct, right?
If that is correct, we unconsciously inform that the user exists.
Is not it a danger to inform that the user exists?

**Comment by andresmoschini** [comment]
> I do not understand much about React, but I think it's all okay.
> 
> Only I have 2 questions `userBlockedByPassword` informs that the user exists but fails when the password is not correct, right?
> If that is correct, we unconsciously inform that the user exists.
> Is not it a danger to inform that the user exists?

No, if I am not wrong it happens when the password is fine but the account has been blocked by a lot of wrong password tries.

**Comment by cbernat** [comment]
> 🚧 WIP DO NOT MERGE!
> 
> Hi team (mainly @mmosquera and @cbernat),
> 
> I am working on these changes, in order to connect with Legacy Doppler backend for Login operation.
> 
> @cbernat, do you have screenshots about how Legacy Doppler deals with these expected errors?

### Configuration in admin in edit user
image

### How errors are shown in login

#### Blocked invalid password
image
Contactanos: https://www.fromdoppler.com/contacto

#### Blocked not payed
image

#### Blocked cancelated
image
Contactanos: https://www.fromdoppler.com/contacto

**Comment by andresmoschini** [comment]
Hi team,

Well, I have reduced the scope of this PR.

By the moment, I am calling _DopplerLegacyClient_, and I am ready to get expected errors, but I am not dealing with them yet (See TODO notes).

I am also sending captcha to backend and restarting the session.

Basically, the pending work is dealing with expected errors. 

Could you review?

**Pull request merged**
