### PR TITLE
refactor: change class components to functional components

### PR DESCRIPTION
**Pull request by cbernat**
Components:

- UpgradePlanForm

Issue: DW-93

### CODE REVIEW

**Comment by andresmoschini** [comment]
🎉❤️ Nice!

I did not read it deeply, but the changes looks fine. Thanks for this work!

> Components:
>     * UpgradePlanForm
>     * ReportsBox
>     * HeaderMessage
>     * HeaderUserMenu

I did not understand. The changes seem only be related to the file _UpgradePlanForm.js_.

**Comment by cbernat** [comment]
> 🎉❤️ Nice!
> 
> I did not read it deeply, but the changes looks fine. Thanks for this work!
> 
> > Components:
> > * UpgradePlanForm
> > * ReportsBox
> > * HeaderMessage
> > * HeaderUserMenu
> 
> I did not understand. The changes seem only be related to the file _UpgradePlanForm.js_.

Yes I've only added one component yet. The others are pending... I will add them next.

**Comment by andresmoschini** [comment]
> Yes I've only added one component yet. The others are pending... I will add them next.

Se puede hacer uno por PR.

**Comment by cbernat** [comment]
Tested in https://cdn.fromdoppler.com/doppler-webapp/demo-build1848/#/reports and in prod 
https://cdn.fromdoppler.com/doppler-webapp/build1848/#/reports merging...

**Pull request merged**
