### PR TITLE
chore(lang): update translations

### PR DESCRIPTION
**Pull request by ramniel**
before (es)
Screen Shot 2021-05-28 at 15 53 03
after (es)
Screen Shot 2021-05-28 at 15 57 21
before (en)
Screen Shot 2021-05-28 at 16 07 42
after (en)
Screen Shot 2021-05-28 at 16 15 48

### CODE REVIEW

**Comment by andresmoschini** [comment]
Nice work!

image

Please reword at least one commit as `fix` because in another case it will not generate a new version and neither a new release.

**Comment by cbernat** [comment]
👍

**Comment by ramniel** [comment]
Test this please.

**Comment by ramniel** [comment]
Test this please.

**Pull request merged**
