### PR TITLE
fix(MasterSubscriber): subscriber status icon

### PR DESCRIPTION
**Pull request by fcoronelmakingsense**
- show subscriber status icon
image

### CODE REVIEW

**Comment by cbernat** [comment]
I thought that the icon was along with a mini description. What do you think @GusBaamonde ?

**Comment by GusBaamonde** [comment]
It is true https://github.com/FromDoppler/Doppler-UI-System/pull/230

**Comment by fcoronelmakingsense** [comment]
image

**Comment by fcoronelmakingsense** [comment]
updated

**Comment by GusBaamonde** [comment]
one Love ❤️

**Pull request merged**
