### PR TITLE
fix(shopify): remove not implemented feature text

### PR DESCRIPTION
**Pull request by cbernat**
As talked with @mvillaseco some features are yet to be implemented. So I'm removing the text reference from Shopify panel.

@mfantinims

### CODE REVIEW

**Comment by andresmoschini** [comment]
Good catch @mvillaseco!

@cbernat, if I am not wrong, it will be ready relatively soon, what do you think about, after merging it, open a new PR reverting this change and add a link in the Jira ticket related to Products integration?

**Comment by cbernat** [comment]
> Good catch @mvillaseco!
> 
> @cbernat, if I am not wrong, it will be ready relatively soon, what do you think about, after merging it, open a new PR reverting this change and add a link in the Jira ticket related to Products integration?

The credit all goes to @mfantinims, he realized, I asked @mvillaseco just to be on the safe side.

**Comment by cbernat** [comment]
> Good catch @mvillaseco!
> 
> @cbernat, if I am not wrong, it will be ready relatively soon, what do you think about, after merging it, open a new PR reverting this change and add a link in the Jira ticket related to Products integration?

I didn't get the last part, add a PR with the revert of this change in a special part of jira?

**Comment by andresmoschini** [comment]
> The credit all goes to @mfantinims, he realized, I asked @mvillaseco just to be on the safe side.

And..., what did I say? :P

**Comment by andresmoschini** [comment]
> I didn't get the last part, add a PR with the revert of this change in a special part of jira?

Claro, quise decir, en el ticket de Jira relacionado con la feature que quitaste del texto, agregar un link al PR que revierte esto. En caso contrario, cuando esté esa feature nadie va a actualizar este texto.

**Comment by cbernat** [comment]
> > I didn't get the last part, add a PR with the revert of this change in a special part of jira?
> 
> Claro, quise decir, en el ticket de Jira relacionado con la feature que quitaste del texto, agregar un link al PR que revierte esto. En caso contrario, cuando esté esa feature nadie va a actualizar este texto.

Mejor dejemos el PR abierto y voy checkeando con los mosqueteros, no se si hay una tarea puntual para esto.

**Pull request merged**
