### PR TITLE
fix: add grid system in unique page views

### PR DESCRIPTION
**Pull request by GusBaamonde**
- add grid system in unique page views

grid-system-page-views

- Add the error in dp-box-shadow

add-grid-system-and-error

### CODE REVIEW

**Comment by andresmoschini** [comment]
Nide! does it also fix the issue with the spinners?

**Comment by GusBaamonde** [comment]
> Nide! does it also fix the issue with the spinners?

In this case we don't have that problem. The problem is in the boxes above.
I will check it in another pr.

**Comment by cbernat** [comment]
Very nice and clean! ❤️

**Pull request merged**
