### PR TITLE
feat: correct use of proxima nova font

### PR DESCRIPTION
**Pull request by GusBaamonde**
webapp-proxima-nova

### CODE REVIEW

**Comment by cbernat** [comment]
Wow https://cdn.fromdoppler.com/doppler-webapp/demo-build3025/#/reports 👍

**Comment by cbernat** [comment]
Did you check all screens? They look different with this change:
https://cdn.fromdoppler.com/doppler-webapp/demo-build3025/#/signup
https://cdn.fromdoppler.com/doppler-webapp/demo-build3025/#/login
https://cdn.fromdoppler.com/doppler-webapp/demo-build3025/#/integrations/shopify
https://cdn.fromdoppler.com/doppler-webapp/demo-build3025/#/new-features
https://cdn.fromdoppler.com/doppler-webapp/demo-build3025/#/plan-selection?promo-code=ALLPLANS

**Comment by GusBaamonde** [comment]
> ¿Revisaste todas las pantallas? Se ven diferentes con este cambio:
> [https://cdn.fromdoppler.com/doppler-webapp/demo-build3025/#/signup ](https://cdn.fromdoppler.com/doppler-webapp/demo-build3025/#/signup)
> [https://cdn.fromdoppler.com/doppler-webapp/demo-build3025/#/login ](https://cdn.fromdoppler.com/doppler-webapp/demo-build3025/#/login)
> [https : //cdn.fromdoppler.com/doppler-webapp/demo-build3025/#/integrations/shopify ](https://cdn.fromdoppler.com/doppler-webapp/demo-build3025/#/integrations/shopify)
> [https://cdn.fromdoppler.com/doppler-webapp/demo-build3025/#/new-features ](https://cdn.fromdoppler.com/doppler-webapp/demo-build3025/#/new-features)
> [https: // cdn .fromdoppler.com / doppler-webapp / demo-build3025 / # / plan-selection? promo-code = ALLPLANS](https://cdn.fromdoppler.com/doppler-webapp/demo-build3025/#/plan-selection?promo-code=ALLPLANS)

It is logical that we have changes in the visual aspect
I review them now with Manu if you can see what we adjust

**Pull request merged**
