### PR TITLE
chore(deps): remove package-lock.json

### PR DESCRIPTION
**Pull request by andresmoschini**
It is to remove this warning:

```
warning package-lock.json found. Your project contains lock files generated by
tools other than Yarn. It is advised not to mix package managers in order to 
avoid resolution inconsistencies caused by unsynchronized lock files. To clear 
this warning, remove package-lock.json.
```

### CODE REVIEW

**Comment by cbernat** [comment]
👍

**Comment by cbernat** [comment]
I'm remembering that dependabot's PR generate a 'package-lock.json' perhaps we need to adjust something in there.

**Comment by andresmoschini** [comment]
> I'm remembering that dependabot's PR generate a 'package-lock.json' perhaps we need to adjust something in there.

I think that Dependabot updates `package-lock.json` or `yarn.lock` if these files exist, if they don't I think that Dependabot does not do anything.

**Pull request merged**
