### PR TITLE
feat(invoices): add breadcrumb in the invoices page

### PR DESCRIPTION
**Pull request by jhoffman-ms**
Added breadcrumb in the invoices page:

image

**Changes:**

- Added the breadcrumb to redirect to: control panel or billing information

**Task:** [DAT-174](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-174)

### CODE REVIEW

**Comment by andresmoschini** [comment]
👏

**Comment by GusBaamonde** [comment]
✌️

**Comment by fgchaio** [comment]
👍

**Comment by cbernat** [comment]
👍

**Pull request merged**
