### PR TITLE
DW-257: change contents viewed in demo

### PR DESCRIPTION
**Pull request by cbernat**
- campaign --> Campaign, campaña --> Campaña
- subscriber --> Subscriber, suscriptor --> Suscriptor
- gdpr --> rgpd (spanish only)

image

https://cdn.fromdoppler.com/doppler-webapp/build2244/#/reports/subscriber-gdpr?email=vpopovich@makingsense.com

image

https://cdn.fromdoppler.com/doppler-webapp/build2244/#/reports/partials-campaigns?campaignId=10011359

image

https://cdn.fromdoppler.com/doppler-webapp/build2244/#/reports/subscriber-history?email=vpopovich@makingsense.com

### CODE REVIEW

**Comment by andresmoschini** [comment]
👍 Is it enough to make this page available for final users?

CC: @lvillalba-ms @mfantinims

**Comment by cbernat** [comment]
@mrunge86 perhaps you are interested in this.

**Comment by cbernat** [comment]
test this please

**Pull request merged**
