### PR TITLE
[DAT-539] - Removed the success message

### PR DESCRIPTION
**Pull request by jhoffman-ms**
Removed the success message when the sumbit was succesfully.

**Changes:**

- Removed the success message in the 'Contact Information' and 'Billing Information'sections when the sumbit was succesfully.
- Updated the UTs.

**Task:** [DAT-539](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-539)

### CODE REVIEW

**Comment by nreal** [comment]
It 's ok for me

**Comment by jhoffman-ms** [comment]
Do you have another feedback or is ready for merge?

**Comment by jcamposmk** [comment]
:+1:

**Pull request merged**
