### PR TITLE
DW-957-remove-duplicate-zoho-css

### PR DESCRIPTION
**Pull request by silsanchez8**
## Modifications:
Remove duplicate stylesheet link from **index.html**, it was in header and before  closing body tag. ( This last one was removed).

@cbernat @andresmoschini @GusBaamonde @lucianaDilizio

### CODE REVIEW

**Comment by cbernat** [comment]
This is the cdn build for your last successful build
production -->https://cdn.fromdoppler.com/doppler-webapp/build3194/#/signup
int --> https://cdn.fromdoppler.com/doppler-webapp/int-build3194/#/signup
qa --> https://cdn.fromdoppler.com/doppler-webapp/qa-build3194/#/signup

**Comment by cbernat** [comment]
@silsanchez8 you could add in the affected region of your change in the commit message, like this:
fix(zoho-chat): remove duplicated stylesheet link

**Review by lucianaDilizio — COMMENTED** [review]
💪

**Comment by GusBaamonde** [comment]
:muscle:

**Comment by cbernat** [comment]
Ready to merge 🚀

**Comment by silsanchez8** [comment]
> This is the cdn build for your last successful build
> production -->https://cdn.fromdoppler.com/doppler-webapp/build3194/#/signup
> int --> https://cdn.fromdoppler.com/doppler-webapp/int-build3194/#/signup
> qa --> https://cdn.fromdoppler.com/doppler-webapp/qa-build3194/#/signup

Ultimo release:  3208

**Pull request merged**
