### PR TITLE
fix: add release tag generation in Jenkinsfile

### PR DESCRIPTION
**Pull request by cbernat**
In an effort to move to the new process for deployment I've added semantic release tag generation in jenkinsfile.

Tasks:
- Disable old tag generation
- Copy into a new file
- Call this file from jenkins pipeline

### CODE REVIEW

**Comment by andresmoschini** [comment]
Let us try this! 🚀

**Comment by andresmoschini** [comment]
> andresmoschini closed this 6 minutes ago

Ooooops, sorry

**Comment by cbernat** [comment]
Test this please.

**Comment by cbernat** [comment]
> > andresmoschini closed this 6 minutes ago
> 
> Ooooops, sorry

:trollface:

**Comment by andresmoschini** [comment]
Creo que no se generó el release porque faltaba esto:

image

Lo pruebo...

**Comment by andresmoschini** [comment]
Al parecer funcionó bien, se generó el release [1.176.1](https://github.com/FromDoppler/doppler-webapp/releases/tag/v1.176.1)

**Comment by andresmoschini** [comment]
Al parecer funcionó bien, se generó el release [1.176.1](https://github.com/FromDoppler/doppler-webapp/releases/tag/v1.176.1)

**Pull request merged**
