### PR TITLE
fix: avoid to try to translate control panel URLs

### PR DESCRIPTION
**Pull request by andresmoschini**
It fixes these errors:

image

### CODE REVIEW

**Comment by andresmoschini** [comment]
@fgchaio @jcamposmk could you review this change?

**Comment by fgchaio** [comment]
I think there are some links that requiere translation.

**Comment by andresmoschini** [comment]
> I think there are some links that requiere translation.

image

I see...

But in that case, it is not the right way to do it.

Maybe we can:
* Translate it here in `control-panel-service.ts`
* Use two different properties, one for URLs as they are and another for keys
* Add all URLs to the language files

**Comment by andresmoschini** [comment]
Closing this PR, I have no time to fix it, but we should.

Let me know if you need help fixing it. Thanks!

**Comment by fgchaio** [comment]
I will create a ticket for this.

**Comment by andresmoschini** [comment]
>     * Translate it here in `control-panel-service.ts`

I think that this is the easiest solution, but we do not have a translation service out of React context. But we could inject it into the call to `getControlPanelSections()`

image

Maybe it is not so elegant, but it is easy and fixes the issue.

**Pull request closed without merging**
