### PR TITLE
[no ticket] Add .editorconfig and eclint plugin

### PR DESCRIPTION
**Pull request by fcoronelmakingsense**
- Add editorconfig based on https://github.com/MakingSense/doppler-feature-toggle-js
- Add Eclint https://github.com/jedmao/eclint to check all rules defined in editorconfig
- Add Eclint task in package.json

### CODE REVIEW

**Comment by andresmoschini** [comment]
Nice! and is it working? I expected to see fixes in some files.

**Comment by fcoronelmakingsense** [comment]
> Nice! and is it working? I expected to see fixes in some files.

Yes! can try with yarn eclint or yarn build :)

**Comment by andresmoschini** [comment]
> > Nice! and is it working? I expected to see fixes in some files.
> 
> Yes! can try with yarn eclint or yarn build :). I add only javascript files

Nice!, but, you should include also the fixes, in another way everybody will have errors.

**Comment by andresmoschini** [comment]
@fcoronelmakingsense confirmed me that there was only one editorconfig error, and it is fixed!
❤️

**Pull request merged**
