### PR TITLE
fix: change site tracking enable method to post

### PR DESCRIPTION
**Pull request by fcoronelmakingsense**
- Change EnableSiteTracking method from get to post

### CODE REVIEW

**Comment by cbernat** [comment]
Also you can test in local env, qa or int.

**Comment by fcoronelmakingsense** [comment]
Tested in https://cdn.fromdoppler.com/doppler-webapp/build779/#/reports

**Comment by andresmoschini** [comment]
> Tested in https://cdn.fromdoppler.com/doppler-webapp/build779/#/reports

❤️  Me too!

**Pull request merged**
