### PR TITLE
DE-554 - Use Session MFE

### PR DESCRIPTION
**Pull request by andresmoschini**
It replaces the WebApp native implementation for listening for Doppler Session updates with a [Session MFE](https://github.com/FromDoppler/doppler-session-mfe)-based implementation.

Pending:

- [x] Test integrated
- [x] Remove console logs

### CODE REVIEW

**Comment by andresmoschini** [comment]
@jcamposmk @diegoamatte I am planning to merge it today, have I your blessing?

**Review by bseguermaking — APPROVED** [review]
:rocket:

**Comment by jcamposmk** [comment]
👍

**Comment by diegoamatte** [comment]
👌

**Pull request merged**
