### PR TITLE
refactor(utils): convert utils.ts to typescript

### PR DESCRIPTION
**Pull request by andresmoschini**
Hi team, now we have types in out _utils_ package :)

### CODE REVIEW

**Comment by cbernat** [comment]
👍

**Comment by fcoronelmakingsense** [comment]
Nice! the idea is in the future move to Typescript? or only the services and common stuff, what do you think?

**Comment by andresmoschini** [comment]
> Nice! the idea is in the future move to Typescript? or only the services and common stuff, what do you think?

I have no preference. I am not sure if we need to define it.

**Pull request merged**
