### PR TITLE
add(release): add build-n-publish

### PR DESCRIPTION
**Pull request by fcoronelmakingsense**

### CODE REVIEW

**Comment by andresmoschini** [comment]
Not so important, but I think that _add_ is not a valid type, at least based on https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type

As @leoslopez [said](https://github.com/MakingSense/doppler-reports-api/pull/4#issuecomment-450920198), at least at the beginning, using this convention will be an extra load for us.

**Comment by andresmoschini** [comment]
Nice work! thanks @fcoronelmakingsense !

**Comment by fcoronelmakingsense** [comment]
> Not so important, but I think that _add_ is not a valid type, at least based on https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type
> 
> As @leoslopez [said](https://github.com/MakingSense/doppler-reports-api/pull/4#issuecomment-450920198), at least at the beginning, using this convention will be an extra load for us.

ok i didn't know that, thanks you!

**Comment by fcoronelmakingsense** [comment]
test this please

**Comment by cbernat** [comment]
Test this please

**Comment by cbernat** [comment]
Test this please

**Pull request merged**
