### PR TITLE
DE-184 Add UX Google Tag Manager

### PR DESCRIPTION
**Pull request by paangaflo**
HU: [DE-184](https://makingsense.atlassian.net/browse/DE-184)

Add script for Google Tag Manager with code GTM-TMMV2DF.

### Google Tag Manager:
- New container that will be used by UX team.
- Official google documentation is used to use multiple containers on the same page.

https://developers.google.com/tag-manager/devguide?hl=en#multiple-containers

### CODE REVIEW

**Comment by jcamposmk** [comment]
You can do "yarn prettier", maybe.

image

**Comment by andresmoschini** [comment]
test this please

**Comment by andresmoschini** [comment]
👍

**Comment by cbernat** [comment]
@paangaflo the commit is not ok, it should've been feat instead of feature. You can check a full detail of conventional commits format [here](https://www.conventionalcommits.org/en/v1.0.0/) The only issue here is that it hasn´t generated any tag for a release,
but don´t worry, this will be published in the next release, when someone uploades any other feature. 😄

**Comment by cbernat** [comment]
@paangaflo You can test this version though in cdn like this https://cdn.fromdoppler.com/doppler-webapp/build3220/#/login?lang=en pointing to production.

**Pull request merged**
