### PR TITLE
feat(SignupConfirmation): add route for datahub tracking

### PR DESCRIPTION
**Pull request by fcoronelmakingsense**
- Add redirect to signup when access for url and signup isnt completed

### CODE REVIEW

**Comment by cbernat** [comment]
Very nice @fcoronelmakingsense !

**Comment by andresmoschini** [comment]
But, I cannot see the redirect to `/signup/confirmation` after submit signup form. Am I missing something?

**Comment by andresmoschini** [comment]
> But, I cannot see the redirect to `/signup/confirmation` after submit signup form. Am I missing something?

Also, having a test for that behavior would be nice.

**Comment by cbernat** [comment]
> > But, I cannot see the redirect to `/signup/confirmation` after submit signup form. Am I missing something?
> 
> Also, having a test for that behavior would be nice.

Yes but how? I thought that too 😄

**Comment by fcoronelmakingsense** [comment]
> But, I cannot see the redirect to `/signup/confirmation` after submit signup form. Am I missing something?

yes you are right, my bad

**Comment by cbernat** [comment]
@fcoronelmakingsense The general idea of this task was to redirect to a new route after signup is ok, in order to allow tracking the access of this confirmation landing url (tracking is done by datahub and analytics that listen to changes in routing, this logic is in `index.js`)

**Comment by fcoronelmakingsense** [comment]
test this please

**Comment by cbernat** [comment]
test this please

**Comment by andresmoschini** [comment]
Nice @fcoronelmakingsense ! it is weird but it is relatively simple and seems to work.

Having a test would be nice, but I understand that it is not so easy. So, if you want, merge as it is, but please keep thinking about how it (or a similar scenario) could be tested in the future.

**Comment by fcoronelmakingsense** [comment]
> Nice @fcoronelmakingsense ! it is weird but it is relatively simple and seems to work.
> 
> Having a test would be nice, but I understand that it is not so easy. So, if you want, merge as it is, but please keep thinking about how it (or a similar scenario) could be tested in the future.

Yes, thanks I will consider it for possible scenarios in the future

**Pull request merged**
