### PR TITLE
Fix background in signup confirmation page

### PR DESCRIPTION
**Pull request by IgnacioRodrigues**
Fix background in signup confirmation page
Screenshot Capture - 2019-04-25 - 18-00-19
Screenshot Capture - 2019-04-25 - 17-59-54

### CODE REVIEW

**Comment by andresmoschini** [comment]
Are you sure that you have applied all the required changes related to https://github.com/FromDoppler/Doppler-UI-System/pull/91 ?

I am asking because, for example, in UI Library you have updated the title level, and here you did not:

image
https://github.com/FromDoppler/Doppler-UI-System/pull/91/files#diff-0cef2955f4eb751ca7fd58b153f305e5R57

image
https://github.com/FromDoppler/doppler-webapp/pull/144/files#diff-ace2f64e6a2fd77cd5e38019e884b379R25

**Comment by IgnacioRodrigues** [comment]
Yes, I miss making that change of title.

**Comment by IgnacioRodrigues** [comment]
> there is not the privacy policy link?

Is no necessary, the privacy policy link is necessary when you have a form. In this case, is a redirection the signup and there isn't form.

**Pull request merged**
