### PR TITLE
chore: add clarification comment in getReferrerHostname

### PR DESCRIPTION
**Pull request by andresmoschini**

### CODE REVIEW

**Comment by andresmoschini** [comment]
@MatiasRoy-Rodriguez thanks for the advice!

I think that it could help.

**Comment by MatiasRoy-Rodriguez** [comment]
> @MatiasRoy-Rodriguez thanks for the advice!
> 
> I think that it could help.

Perfect 💪

**Comment by jcamposmk** [comment]
👍

**Pull request merged**
