### PR TITLE
fix(BannerUpgrade): fix object links

### PR DESCRIPTION
**Pull request by silsanchez8**
## Modifications: https://makingsense.atlassian.net/browse/DW-1135
* fix(BannerUpgrade): fix object links

image

image

image

### CODE REVIEW

**Comment by cbernat** [comment]
Perhaps it would be nice if we could add some test to validate that the link url is not #. Perhaps add this in an existent test.

**Comment by cbernat** [comment]
Tested for free and plus and it´s ok https://cdn.fromdoppler.com/doppler-webapp/int-build3840/#/plan-selection. 😄

**Comment by jcamposmk** [comment]
:+1:

**Pull request merged**
